In [1]:
import numpy as np
import pandas as pd

In [13]:
active = pd.read_json(r"/home/mr_robot/datasets/celestrak/gp/active.json")
satcat = pd.read_csv(r"/home/mr_robot/datasets/celestrak/satcat/satcat.csv")
print(active.columns.tolist())
print()
print()


print(satcat.columns.tolist())
active

['OBJECT_NAME', 'OBJECT_ID', 'EPOCH', 'MEAN_MOTION', 'ECCENTRICITY', 'INCLINATION', 'RA_OF_ASC_NODE', 'ARG_OF_PERICENTER', 'MEAN_ANOMALY', 'EPHEMERIS_TYPE', 'CLASSIFICATION_TYPE', 'NORAD_CAT_ID', 'ELEMENT_SET_NO', 'REV_AT_EPOCH', 'BSTAR', 'MEAN_MOTION_DOT', 'MEAN_MOTION_DDOT']


['OBJECT_NAME', 'OBJECT_ID', 'NORAD_CAT_ID', 'OBJECT_TYPE', 'OPS_STATUS_CODE', 'OWNER', 'LAUNCH_DATE', 'LAUNCH_SITE', 'DECAY_DATE', 'PERIOD', 'INCLINATION', 'APOGEE', 'PERIGEE', 'RCS', 'ORBIT_CENTER', 'ORBIT_TYPE']

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,CALSPHERE 1,1964-063C,2026-06-08T03:50:39.960672,13.766137,0.002508,90.2237,71.5582,326.0477,129.7710,0,U,900,999,7018,0.000606,6.040000e-06,0.0
1,CALSPHERE 2,1964-063E,2026-06-08T05:49:38.059104,13.528998,0.001661,90.2378,75.5801,251.8811,231.5976,0,U,902,999,85505,0.000038,3.400000e-07,0.0
2,LCS 1,1965-034C,2026-06-07T18:44:24.906912,9.893106,0.001238,32.1362,199.3633,88.6229,271.5686,0,U,1361,999,20895,-0.001621,-4.000000e-08,0.0
3,TEMPSAT 1,1965-065E,2026-06-08T05:02:26.219616,13.335936,0.006762,89.9993,212.5929,273.9661,153.9017,0,U,1512,999,95885,0.000037,2.700000e-07,0.0
4,CALSPHERE 4A,1965-065H,2026-06-08T03:41:54.407616,13.362767,0.007142,89.8976,122.5769,127.7636,244.7139,0,U,1520,999,96150,0.000250,1.400000e-06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15625,GUOWANG TEST OBJECT C,2026-120C,2026-06-07T00:06:59.203296,15.395217,0.000956,54.9981,73.5721,307.3825,52.6333,0,U,69322,999,112,0.000454,1.775500e-04,0.0
15626,GUOWANG TEST OBJECT D,2026-120D,2026-06-04T15:59:40.712352,15.397045,0.000800,55.0029,84.1123,301.7889,58.2360,0,U,69323,999,76,0.000808,3.213700e-04,0.0
15627,QIANFAN-163,2026-121A,2026-06-07T22:57:09.254304,13.603512,0.001920,89.0166,301.4497,214.2828,145.7091,0,U,69325,999,90,0.000027,3.200000e-07,0.0
15628,QIANFAN-164,2026-121B,2026-06-08T07:45:37.541088,13.605046,0.001861,89.0162,301.4118,214.4374,145.5577,0,U,69326,999,95,0.000162,1.340000e-06,0.0
15629,SZ-22 MODULE,2025-272C,2026-06-07T21:26:14.951904,15.598490,0.000771,41.4812,18.5944,10.7698,349.3304,0,U,69328,999,187,0.000265,2.169900e-04,0.0

In [19]:
catalog = pd.merge(
    active,
    satcat,
    on=["OBJECT_NAME",
"OBJECT_ID",
"NORAD_CAT_ID",
"INCLINATION"],
    how="left"
)
catalog.dropna(axis=1,inplace=True)

data=pd.read_csv(r"/home/mr_robot/datasets/processed/collision_event.csv")
data

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,CALSPHERE 1,1964-063C,2026-06-08T03:50:39.960672,13.766137,0.002508,90.2237,71.5582,326.0477,129.7710,0,U,900,999,7018,0.000606,6.040000e-06,0.0
1,CALSPHERE 2,1964-063E,2026-06-08T05:49:38.059104,13.528998,0.001661,90.2378,75.5801,251.8811,231.5976,0,U,902,999,85505,0.000038,3.400000e-07,0.0
2,LCS 1,1965-034C,2026-06-07T18:44:24.906912,9.893106,0.001238,32.1362,199.3633,88.6229,271.5686,0,U,1361,999,20895,-0.001621,-4.000000e-08,0.0
3,TEMPSAT 1,1965-065E,2026-06-08T05:02:26.219616,13.335936,0.006762,89.9993,212.5929,273.9661,153.9017,0,U,1512,999,95885,0.000037,2.700000e-07,0.0
4,CALSPHERE 4A,1965-065H,2026-06-08T03:41:54.407616,13.362767,0.007142,89.8976,122.5769,127.7636,244.7139,0,U,1520,999,96150,0.000250,1.400000e-06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15625,GUOWANG TEST OBJECT C,2026-120C,2026-06-07T00:06:59.203296,15.395217,0.000956,54.9981,73.5721,307.3825,52.6333,0,U,69322,999,112,0.000454,1.775500e-04,0.0
15626,GUOWANG TEST OBJECT D,2026-120D,2026-06-04T15:59:40.712352,15.397045,0.000800,55.0029,84.1123,301.7889,58.2360,0,U,69323,999,76,0.000808,3.213700e-04,0.0
15627,QIANFAN-163,2026-121A,2026-06-07T22:57:09.254304,13.603512,0.001920,89.0166,301.4497,214.2828,145.7091,0,U,69325,999,90,0.000027,3.200000e-07,0.0
15628,QIANFAN-164,2026-121B,2026-06-08T07:45:37.541088,13.605046,0.001861,89.0162,301.4118,214.4374,145.5577,0,U,69326,999,95,0.000162,1.340000e-06,0.0
15629,SZ-22 MODULE,2025-272C,2026-06-07T21:26:14.951904,15.598490,0.000771,41.4812,18.5944,10.7698,349.3304,0,U,69328,999,187,0.000265,2.169900e-04,0.0

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,CALSPHERE 1,1964-063C,2026-06-08T03:50:39.960672,13.766137,0.002508,90.2237,71.5582,326.0477,129.7710,0,U,900,999,7018,0.000606,6.040000e-06,0.0
1,CALSPHERE 2,1964-063E,2026-06-08T05:49:38.059104,13.528998,0.001661,90.2378,75.5801,251.8811,231.5976,0,U,902,999,85505,0.000038,3.400000e-07,0.0
2,LCS 1,1965-034C,2026-06-07T18:44:24.906912,9.893106,0.001238,32.1362,199.3633,88.6229,271.5686,0,U,1361,999,20895,-0.001621,-4.000000e-08,0.0
3,TEMPSAT 1,1965-065E,2026-06-08T05:02:26.219616,13.335936,0.006762,89.9993,212.5929,273.9661,153.9017,0,U,1512,999,95885,0.000037,2.700000e-07,0.0
4,CALSPHERE 4A,1965-065H,2026-06-08T03:41:54.407616,13.362767,0.007142,89.8976,122.5769,127.7636,244.7139,0,U,1520,999,96150,0.000250,1.400000e-06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15625,GUOWANG TEST OBJECT C,2026-120C,2026-06-07T00:06:59.203296,15.395217,0.000956,54.9981,73.5721,307.3825,52.6333,0,U,69322,999,112,0.000454,1.775500e-04,0.0
15626,GUOWANG TEST OBJECT D,2026-120D,2026-06-04T15:59:40.712352,15.397045,0.000800,55.0029,84.1123,301.7889,58.2360,0,U,69323,999,76,0.000808,3.213700e-04,0.0
15627,QIANFAN-163,2026-121A,2026-06-07T22:57:09.254304,13.603512,0.001920,89.0166,301.4497,214.2828,145.7091,0,U,69325,999,90,0.000027,3.200000e-07,0.0
15628,QIANFAN-164,2026-121B,2026-06-08T07:45:37.541088,13.605046,0.001861,89.0162,301.4118,214.4374,145.5577,0,U,69326,999,95,0.000162,1.340000e-06,0.0
15629,SZ-22 MODULE,2025-272C,2026-06-07T21:26:14.951904,15.598490,0.000771,41.4812,18.5944,10.7698,349.3304,0,U,69328,999,187,0.000265,2.169900e-04,0.0

In [27]:
kp = pd.read_json(r"/home/mr_robot/datasets/noaa/geomagnetic/kp_index.json")
solar = pd.read_json(r"/home/mr_robot/datasets/noaa/solar/solar_wind.json")
mag = pd.read_json(r"/home/mr_robot/datasets/noaa/solar/magnetic_field.json")

              time_tag    Kp  a_running  station_count
0  2026-06-01T00:00:00  2.00          7              8
1  2026-06-01T03:00:00  1.00          4              8
2  2026-06-01T06:00:00  1.67          6              8
3  2026-06-01T09:00:00  1.67          6              8
4  2026-06-01T12:00:00  2.67         12              8
                  time_tag  density  speed  temperature
0  2026-06-07 13:14:00.000     0.85  560.6       116327
1  2026-06-07 13:15:00.000     0.94  554.2       109943
2  2026-06-07 13:16:00.000     0.80  556.0       125935
3  2026-06-07 13:17:00.000     0.91  540.9       115662
4  2026-06-07 13:18:00.000     0.97  541.7       118567
                  time_tag  bx_gsm  by_gsm  bz_gsm  lon_gsm  lat_gsm    bt
0  2026-06-07 13:17:00.000   -3.42    3.45   -1.53   134.71   -17.47  5.09
1  2026-06-07 13:18:00.000   -3.53    3.22   -1.67   137.64   -19.29  5.07
2  2026-06-07 13:19:00.000   -3.24    3.27   -1.80   134.77   -21.31  4.94
3  2026-06-07 13:20:00.000   -3.09    2.89   -2.68   136.87   -32.37  5.01
4  2026-06-07 13:21:00.000   -3.11    2.68   -2.73   139.22   -33.58  4.93

In [34]:
kp["time_tag"] = pd.to_datetime(kp["time_tag"])
solar["time_tag"] = pd.to_datetime(solar["time_tag"])

space_weather = (
    kp.merge(
        solar,
        on="time_tag",
        how="outer"
    )
    .merge(
        mag,
        on="time_tag",
        how="outer"
    )
)
df=pd.merge_asof(
    kp.sort_values("time_tag"),
    solar.sort_values("time_tag"),
    on="time_tag",
    direction="nearest"
)
df

ValueError: You are trying to merge on datetime64[ns] and object columns for key 'time_tag'. If you wish to proceed you should use pd.concat